title: designed for play games
author: Johnson Earls
email: designedforplaygames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  designed for playâ„¢ is a one-person game studio.

# social links
twitter_username: designedforplay
github_username:  designedforplaygames

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
